### ISSUE TITLE
Readouts keep disapearing

### ISSUE THREAD

**Issue by TrotFoxGreyfoot** [LazeMSS/OctoPrint-TopTemp#12] opened 2021-01-25 14:45 UTC
Hi!

I love the concept but I've noticed that the feedback readouts keep disapearing every few seconds, resulting in the display length shortening to only the setpoints. I see a flag icon pop up when the readback disapears but don't see a reference to it in the docs so I'm not sure what it means? Mostly it's just slightly irritating but a stable display length might be something to look at.

Thanks,
Landon

Normal:
![image](https://user-images.githubusercontent.com/77975889/105720520-21a84980-5ee9-11eb-8420-cb1e1b177d96.png)

Lost T0/Shortened:
![image](https://user-images.githubusercontent.com/77975889/105720636-42709f00-5ee9-11eb-8a83-083706d280c3.png)

**Comment by LazeMSS** [comment] 2021-01-25 19:00
What version are you running?

**Comment by LazeMSS** [comment] 2021-01-25 19:01
It looks like the previous version - 0.0.0.1 - please try updating to 0.0.0.2

**Comment by LazeMSS** [comment] 2021-01-25 19:05
Are the target temperature is not show when the target is reached - instead of showing 200/200 it just displays 200 and a checkered flag to show its reached the target.
You can uncheck "Show target progress"

**Comment by LazeMSS** [comment] 2021-01-25 19:09
Closing - its by design - I might add an option to always show target temperature :)

**Closed by LazeMSS** 2021-01-25 19:09 UTC
